system:
    default:
        content_view:
            full:
                landing_page:
                    template: "EzLandingPageLayoutsBundle:full:landing_page.html.twig"
                    match:
                        Identifier\ContentType: [landing_page]
